/**
 * seed.js — Run once to set up the database schema and insert songs.
 *
 * Usage:
 *   npm run seed
 *
 * To add more songs later, just INSERT into the songs table directly,
 * or import a CSV with:
 *   psql $DATABASE_URL -c "\copy songs(title,artist,era,decade) FROM 'newsongs.csv' CSV HEADER"
 *
 * The `deezer_query` column is auto-generated by a DB trigger so you never
 * have to maintain it manually.
 */

require('dotenv').config();
const pool = require('./db');

// ─── Schema ────────────────────────────────────────────────────────────────────
const CREATE_TABLE = `
  CREATE TABLE IF NOT EXISTS songs (
    id            SERIAL PRIMARY KEY,
    title         TEXT        NOT NULL,
    artist        TEXT        NOT NULL,
    -- era is a broad category for filtering (60s70s, 80s90s, 2000s, modern)
    era           TEXT        NOT NULL DEFAULT 'all',
    -- decade for finer filtering if needed later (1960, 1970, 1980, etc.)
    decade        SMALLINT,
    -- deezer_query is the search string sent to the Deezer API.
    -- Stored here so it can be tuned per-song without code changes.
    deezer_query  TEXT        NOT NULL,
    -- preview_cache stores a known-good Deezer preview URL so we don't
    -- re-search on every game. Cleared nightly if desired.
    preview_cache TEXT,
    preview_cached_at TIMESTAMPTZ,
    -- soft-delete: set enabled=false to retire a song without deleting it
    enabled       BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  -- Index for random-draw queries filtered by era
  CREATE INDEX IF NOT EXISTS idx_songs_era_enabled ON songs(era, enabled);

  -- Full-text search index in case you want a search UI later
  CREATE INDEX IF NOT EXISTS idx_songs_fts
    ON songs USING GIN (to_tsvector('english', title || ' ' || artist));
`;

// ─── Seed data ─────────────────────────────────────────────────────────────────
// deezer_query uses `artist:"X" track:"Y" karaoke` to target instrumental/
// karaoke versions. Deezer has a huge catalog of these.
const SONGS = [
  // 60s & 70s
  ['Bohemian Rhapsody',              'Queen',                    '60s70s', 1975, 'artist:"Queen" track:"Bohemian Rhapsody" karaoke'],
  ['Hotel California',               'Eagles',                   '60s70s', 1977, 'artist:"Eagles" track:"Hotel California" instrumental'],
  ['Stairway to Heaven',             'Led Zeppelin',             '60s70s', 1971, 'artist:"Led Zeppelin" track:"Stairway to Heaven" instrumental'],
  ['Imagine',                        'John Lennon',              '60s70s', 1971, 'artist:"John Lennon" track:"Imagine" karaoke'],
  ['Hey Jude',                       'The Beatles',              '60s70s', 1968, 'artist:"Beatles" track:"Hey Jude" karaoke'],
  ['Let It Be',                      'The Beatles',              '60s70s', 1970, 'artist:"Beatles" track:"Let It Be" karaoke'],
  ['Purple Haze',                    'Jimi Hendrix',             '60s70s', 1967, 'artist:"Jimi Hendrix" track:"Purple Haze" instrumental'],
  ['Respect',                        'Aretha Franklin',          '60s70s', 1967, 'artist:"Aretha Franklin" track:"Respect" karaoke'],
  ['Good Vibrations',                'The Beach Boys',           '60s70s', 1966, 'artist:"Beach Boys" track:"Good Vibrations" karaoke'],
  ['Superstition',                   'Stevie Wonder',            '60s70s', 1972, 'artist:"Stevie Wonder" track:"Superstition" karaoke'],
  ['Like a Rolling Stone',           'Bob Dylan',                '60s70s', 1965, 'artist:"Bob Dylan" track:"Like a Rolling Stone" karaoke'],
  ["What's Going On",                'Marvin Gaye',              '60s70s', 1971, 'artist:"Marvin Gaye" track:"What\'s Going On" karaoke'],
  ['Satisfaction',                   'The Rolling Stones',       '60s70s', 1965, 'artist:"Rolling Stones" track:"Satisfaction" karaoke'],
  ['Dancing Queen',                  'ABBA',                     '60s70s', 1976, 'artist:"ABBA" track:"Dancing Queen" karaoke'],
  ['Born to Run',                    'Bruce Springsteen',        '60s70s', 1975, 'artist:"Bruce Springsteen" track:"Born to Run" karaoke'],
  ['American Pie',                   'Don McLean',               '60s70s', 1971, 'artist:"Don McLean" track:"American Pie" karaoke'],
  ['Piano Man',                      'Billy Joel',               '60s70s', 1973, 'artist:"Billy Joel" track:"Piano Man" karaoke'],
  ['Dream On',                       'Aerosmith',                '60s70s', 1973, 'artist:"Aerosmith" track:"Dream On" karaoke'],
  ['Roxanne',                        'The Police',               '60s70s', 1978, 'artist:"The Police" track:"Roxanne" karaoke'],
  ['Johnny B. Goode',                'Chuck Berry',              '60s70s', 1958, 'artist:"Chuck Berry" track:"Johnny B Goode" instrumental'],
  // 80s & 90s
  ['Billie Jean',                    'Michael Jackson',          '80s90s', 1983, 'artist:"Michael Jackson" track:"Billie Jean" karaoke'],
  ["Sweet Child O' Mine",            "Guns N' Roses",            '80s90s', 1988, 'artist:"Guns N Roses" track:"Sweet Child O Mine" karaoke'],
  ['Smells Like Teen Spirit',        'Nirvana',                  '80s90s', 1991, 'artist:"Nirvana" track:"Smells Like Teen Spirit" karaoke'],
  ['Take On Me',                     'a-ha',                     '80s90s', 1985, 'artist:"a-ha" track:"Take On Me" karaoke'],
  ["Don't Stop Believin'",           'Journey',                  '80s90s', 1981, 'artist:"Journey" track:"Don\'t Stop Believin" karaoke'],
  ['Every Breath You Take',          'The Police',               '80s90s', 1983, 'artist:"The Police" track:"Every Breath You Take" karaoke'],
  ['Jump',                           'Van Halen',                '80s90s', 1984, 'artist:"Van Halen" track:"Jump" karaoke'],
  ['With or Without You',            'U2',                       '80s90s', 1987, 'artist:"U2" track:"With or Without You" karaoke'],
  ['Purple Rain',                    'Prince',                   '80s90s', 1984, 'artist:"Prince" track:"Purple Rain" karaoke'],
  ["Livin' on a Prayer",             'Bon Jovi',                 '80s90s', 1986, 'artist:"Bon Jovi" track:"Livin on a Prayer" karaoke'],
  ['Thriller',                       'Michael Jackson',          '80s90s', 1982, 'artist:"Michael Jackson" track:"Thriller" karaoke'],
  ['Girls Just Want to Have Fun',    'Cyndi Lauper',             '80s90s', 1983, 'artist:"Cyndi Lauper" track:"Girls Just Want to Have Fun" karaoke'],
  ['Africa',                         'Toto',                     '80s90s', 1982, 'artist:"Toto" track:"Africa" karaoke'],
  ['Everybody Wants to Rule the World', 'Tears for Fears',      '80s90s', 1985, 'artist:"Tears for Fears" track:"Everybody Wants to Rule the World" karaoke'],
  ['Come as You Are',                'Nirvana',                  '80s90s', 1991, 'artist:"Nirvana" track:"Come as You Are" karaoke'],
  ['Welcome to the Jungle',          "Guns N' Roses",            '80s90s', 1987, 'artist:"Guns N Roses" track:"Welcome to the Jungle" karaoke'],
  ['Losing My Religion',             'R.E.M.',                   '80s90s', 1991, 'artist:"REM" track:"Losing My Religion" karaoke'],
  ['Under the Bridge',               'Red Hot Chili Peppers',    '80s90s', 1992, 'artist:"Red Hot Chili Peppers" track:"Under the Bridge" karaoke'],
  ['No Scrubs',                      'TLC',                      '80s90s', 1999, 'artist:"TLC" track:"No Scrubs" karaoke'],
  ['Waterfalls',                     'TLC',                      '80s90s', 1994, 'artist:"TLC" track:"Waterfalls" karaoke'],
  ["Gangsta's Paradise",             'Coolio',                   '80s90s', 1995, 'artist:"Coolio" track:"Gangsta\'s Paradise" karaoke'],
  ['Wannabe',                        'Spice Girls',              '80s90s', 1996, 'artist:"Spice Girls" track:"Wannabe" karaoke'],
  ['...Baby One More Time',          'Britney Spears',           '80s90s', 1998, 'artist:"Britney Spears" track:"Baby One More Time" karaoke'],
  ['Creep',                          'Radiohead',                '80s90s', 1992, 'artist:"Radiohead" track:"Creep" karaoke'],
  ['Black Hole Sun',                 'Soundgarden',              '80s90s', 1994, 'artist:"Soundgarden" track:"Black Hole Sun" karaoke'],
  // 2000s
  ['Crazy in Love',                  'Beyoncé',                  '2000s',  2003, 'artist:"Beyonce" track:"Crazy in Love" karaoke'],
  ['In Da Club',                     '50 Cent',                  '2000s',  2003, 'artist:"50 Cent" track:"In Da Club" karaoke'],
  ['Since U Been Gone',              'Kelly Clarkson',           '2000s',  2004, 'artist:"Kelly Clarkson" track:"Since U Been Gone" karaoke'],
  ['Hey Ya!',                        'OutKast',                  '2000s',  2003, 'artist:"OutKast" track:"Hey Ya" karaoke'],
  ['Yeah!',                          'Usher',                    '2000s',  2004, 'artist:"Usher" track:"Yeah" karaoke'],
  ['Lose Yourself',                  'Eminem',                   '2000s',  2002, 'artist:"Eminem" track:"Lose Yourself" karaoke'],
  ['Umbrella',                       'Rihanna',                  '2000s',  2007, 'artist:"Rihanna" track:"Umbrella" karaoke'],
  ['Rolling in the Deep',            'Adele',                    '2000s',  2010, 'artist:"Adele" track:"Rolling in the Deep" karaoke'],
  ['Bad Romance',                    'Lady Gaga',                '2000s',  2009, 'artist:"Lady Gaga" track:"Bad Romance" karaoke'],
  ['Single Ladies',                  'Beyoncé',                  '2000s',  2008, 'artist:"Beyonce" track:"Single Ladies" karaoke'],
  ['Poker Face',                     'Lady Gaga',                '2000s',  2008, 'artist:"Lady Gaga" track:"Poker Face" karaoke'],
  ['Gold Digger',                    'Kanye West',               '2000s',  2005, 'artist:"Kanye West" track:"Gold Digger" karaoke'],
  ['Boulevard of Broken Dreams',     'Green Day',                '2000s',  2004, 'artist:"Green Day" track:"Boulevard of Broken Dreams" karaoke'],
  ['Mr. Brightside',                 'The Killers',              '2000s',  2003, 'artist:"The Killers" track:"Mr Brightside" karaoke'],
  ['Somebody That I Used to Know',   'Gotye',                    '2000s',  2011, 'artist:"Gotye" track:"Somebody That I Used to Know" karaoke'],
  ['I Gotta Feeling',                'The Black Eyed Peas',      '2000s',  2009, 'artist:"Black Eyed Peas" track:"I Gotta Feeling" karaoke'],
  ['Party in the USA',               'Miley Cyrus',              '2000s',  2009, 'artist:"Miley Cyrus" track:"Party in the USA" karaoke'],
  ["Hips Don't Lie",                 'Shakira',                  '2000s',  2005, 'artist:"Shakira" track:"Hips Don\'t Lie" karaoke'],
  ['Toxic',                          'Britney Spears',           '2000s',  2003, 'artist:"Britney Spears" track:"Toxic" karaoke'],
  ['SexyBack',                       'Justin Timberlake',        '2000s',  2006, 'artist:"Justin Timberlake" track:"SexyBack" karaoke'],
  ['Beautiful Day',                  'U2',                       '2000s',  2000, 'artist:"U2" track:"Beautiful Day" karaoke'],
  // Modern (2010+)
  ['Blinding Lights',                'The Weeknd',               'modern', 2019, 'artist:"The Weeknd" track:"Blinding Lights" karaoke'],
  ['Shape of You',                   'Ed Sheeran',               'modern', 2017, 'artist:"Ed Sheeran" track:"Shape of You" karaoke'],
  ['Uptown Funk',                    'Mark Ronson ft. Bruno Mars','modern', 2014, 'artist:"Mark Ronson" track:"Uptown Funk" karaoke'],
  ['Happy',                          'Pharrell Williams',        'modern', 2013, 'artist:"Pharrell Williams" track:"Happy" karaoke'],
  ['Thinking Out Loud',              'Ed Sheeran',               'modern', 2014, 'artist:"Ed Sheeran" track:"Thinking Out Loud" karaoke'],
  ['Stay With Me',                   'Sam Smith',                'modern', 2014, 'artist:"Sam Smith" track:"Stay With Me" karaoke'],
  ['Old Town Road',                  'Lil Nas X',                'modern', 2018, 'artist:"Lil Nas X" track:"Old Town Road" karaoke'],
  ['drivers license',                'Olivia Rodrigo',           'modern', 2021, 'artist:"Olivia Rodrigo" track:"drivers license" karaoke'],
  ['As It Was',                      'Harry Styles',             'modern', 2022, 'artist:"Harry Styles" track:"As It Was" karaoke'],
  ['Good 4 U',                       'Olivia Rodrigo',           'modern', 2021, 'artist:"Olivia Rodrigo" track:"Good 4 U" karaoke'],
  ['Levitating',                     'Dua Lipa',                 'modern', 2020, 'artist:"Dua Lipa" track:"Levitating" karaoke'],
  ['Watermelon Sugar',               'Harry Styles',             'modern', 2019, 'artist:"Harry Styles" track:"Watermelon Sugar" karaoke'],
  ['Dynamite',                       'BTS',                      'modern', 2020, 'artist:"BTS" track:"Dynamite" karaoke'],
  ['Anti-Hero',                      'Taylor Swift',             'modern', 2022, 'artist:"Taylor Swift" track:"Anti-Hero" karaoke'],
  ['Flowers',                        'Miley Cyrus',              'modern', 2023, 'artist:"Miley Cyrus" track:"Flowers" karaoke'],
  ['Cruel Summer',                   'Taylor Swift',             'modern', 2019, 'artist:"Taylor Swift" track:"Cruel Summer" karaoke'],
  ['Shake It Off',                   'Taylor Swift',             'modern', 2014, 'artist:"Taylor Swift" track:"Shake It Off" karaoke'],
  ["God's Plan",                     'Drake',                    'modern', 2018, 'artist:"Drake" track:"God\'s Plan" karaoke'],
  ['Peaches',                        'Justin Bieber',            'modern', 2021, 'artist:"Justin Bieber" track:"Peaches" karaoke'],
  ['Montero (Call Me By Your Name)', 'Lil Nas X',                'modern', 2021, 'artist:"Lil Nas X" track:"Montero" karaoke'],
  ['Save Your Tears',                'The Weeknd',               'modern', 2020, 'artist:"The Weeknd" track:"Save Your Tears" karaoke'],
  ['Shivers',                        'Ed Sheeran',               'modern', 2021, 'artist:"Ed Sheeran" track:"Shivers" karaoke'],
  ['Heat Waves',                     'Glass Animals',            'modern', 2020, 'artist:"Glass Animals" track:"Heat Waves" karaoke'],
  ['Unholy',                         'Sam Smith & Kim Petras',   'modern', 2022, 'artist:"Sam Smith" track:"Unholy" karaoke'],
  ['Sunflower',                      'Post Malone',              'modern', 2018, 'artist:"Post Malone" track:"Sunflower" karaoke'],
  ['Rockstar',                       'Post Malone',              'modern', 2017, 'artist:"Post Malone" track:"Rockstar" karaoke'],
  ['bad guy',                        'Billie Eilish',            'modern', 2019, 'artist:"Billie Eilish" track:"bad guy" karaoke'],
  ['Therefore I Am',                 'Billie Eilish',            'modern', 2020, 'artist:"Billie Eilish" track:"Therefore I Am" karaoke'],
  ['Lovely',                         'Billie Eilish & Khalid',   'modern', 2018, 'artist:"Billie Eilish" track:"Lovely" karaoke'],
  ['Calm Down',                      'Rema & Selena Gomez',      'modern', 2022, 'artist:"Rema" track:"Calm Down" karaoke'],
  ['Circles',                        'Post Malone',              'modern', 2019, 'artist:"Post Malone" track:"Circles" karaoke'],
];

async function seed() {
  const client = await pool.connect();
  try {
    console.log('📦 Creating schema…');
    await client.query(CREATE_TABLE);

    console.log(`🎵 Inserting ${SONGS.length} songs…`);
    let inserted = 0, skipped = 0;

    for (const [title, artist, era, decade, deezer_query] of SONGS) {
      const res = await client.query(
        `INSERT INTO songs (title, artist, era, decade, deezer_query)
         VALUES ($1, $2, $3, $4, $5)
         ON CONFLICT DO NOTHING
         RETURNING id`,
        [title, artist, era, decade, deezer_query]
      );
      res.rowCount > 0 ? inserted++ : skipped++;
    }

    const { rows } = await client.query('SELECT COUNT(*) FROM songs WHERE enabled = true');
    console.log(`✅ Done. Inserted: ${inserted}, Skipped (already exist): ${skipped}`);
    console.log(`📊 Total enabled songs in DB: ${rows[0].count}`);
  } finally {
    client.release();
    await pool.end();
  }
}

seed().catch(err => {
  console.error('Seed failed:', err.message);
  process.exit(1);
});
